apiVersion: v1
data:
  bot-token: OTI3NzAwNzI1OkFBRVZadkhDaVd2WlJkcmtqOHdoUmFZeGJtN2pwT3lHeXFB
  chat-id: LTM3NTkxODA4NQ==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"spark-secret","creationTimestamp":null},"data":{"bot-token":"OTI3NzAwNzI1OkFBRVZadkhDaVd2WlJkcmtqOHdoUmFZeGJtN2pwT3lHeXFB","chat-id":"LTM3NTkxODA4NQ=="}}
  creationTimestamp: 2020-01-18T23:56:22Z
  name: spark-secret
  namespace: default
  resourceVersion: "35877"
  selfLink: /api/v1/namespaces/default/secrets/spark-secret
  uid: 881d4538-052d-4270-aadf-493f57a0431c
type: Opaque
