FROM python:3
WORKDIR /app
ENV FLASK_APP=video_processing_service.py
COPY . .
RUN apt-get update && apt-get install -y ffmpeg && pip install --no-cache-dir -r requirements.txt
CMD ["python", "-m", "flask", "run", "-h", "0.0.0.0"]
