apiVersion: v1
data:
  DB_PASSWORD: bG9nUFIyMCE=
  DB_USER: bG9nX3VzZXI=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"video-processing-secret","creationTimestamp":null},"data":{"DB_PASSWORD":"bG9nUFIyMCE=","DB_USER":"bG9nX3VzZXI="}}
  creationTimestamp: "2020-01-17T20:34:38Z"
  name: video-processing-secret
  namespace: default
  resourceVersion: "196032"
  selfLink: /api/v1/namespaces/default/secrets/video-processing-secret
  uid: d9851f19-e88c-4f40-bb74-9628e2c821ef
type: Opaque
