apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processing
spec:
  selector:
    matchLabels:
      app: video-processing
  template:
    metadata:
      labels:
        app: video-processing
    spec:
      containers:
      - name: video-processing
        image: gdev96/video-processing-service:2.0.0
        envFrom:
          - configMapRef:
              name: video-processing-env
          - secretRef:
              name: video-processing-secret
        volumeMounts:
          - mountPath: /var/video
            name: storage
          - mountPath: /var/videofiles
            name: storage
      initContainers:
      - name: wait-kafka
        image: gdev96/kafka-client:1.0.0
        command: ["sh", "-c", "kafka-console-producer.sh --broker-list $(KAFKA_ADDRESS) --topic $(KAFKA_MAIN_TOPIC)"]
        envFrom:
        - configMapRef:
            name: video-processing-env
      volumes:
      - name: storage
        hostPath:
          path: /storage-volume
          type: DirectoryOrCreate
