apiVersion: v1
data:
  MYSQL_PASSWORD: bG9nUFIyMCE=
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_USER: bG9nX3VzZXI=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"log-db-secret","creationTimestamp":null},"data":{"MYSQL_PASSWORD":"bG9nUFIyMCE=","MYSQL_ROOT_PASSWORD":"cm9vdA==","MYSQL_USER":"bG9nX3VzZXI="}}
  creationTimestamp: "2020-01-13T19:56:36Z"
  name: log-db-secret
  namespace: default
  resourceVersion: "61737"
  selfLink: /api/v1/namespaces/default/secrets/log-db-secret
  uid: 43bf76cd-715a-4565-8341-5afd9f1b1b58
type: Opaque
