apiVersion: v1
data:
  MYSQL_DATABASE: log
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"log-db-env","creationTimestamp":null},"data":{"MYSQL_DATABASE":"log"}}
  creationTimestamp: "2020-01-10T18:40:44Z"
  name: log-db-env
  namespace: default
  resourceVersion: "37557"
  selfLink: /api/v1/namespaces/default/configmaps/log-db-env
  uid: f095f5b2-af40-4390-bfc5-84a994339cac
