apiVersion: v1
data:
  DB_HOST: log-db
  DB_NAME: log
  KAFKA_ADDRESS: apache-kafka:9092
  KAFKA_MAIN_TOPIC: logs
  PRODUCTION_TIME: "10"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"spout-env","creationTimestamp":null},"data":{"DB_HOST":"log-db","DB_NAME":"log","KAFKA_ADDRESS":"apache-kafka:9092","KAFKA_MAIN_TOPIC":"logs","PRODUCTION_TIME":"10"}}
  creationTimestamp: 2020-01-18T23:56:22Z
  name: spout-env
  namespace: default
  resourceVersion: "35873"
  selfLink: /api/v1/namespaces/default/configmaps/spout-env
  uid: 587dd71f-365b-4323-8be9-24e699e65bfe
