apiVersion: apps/v1
kind: Deployment
metadata:
  name: spout
spec:
  selector:
    matchLabels:
      app: spout
  template:
    metadata:
      labels:
        app: spout
    spec:
      containers:
      - name: spout
        image: spout:1.0.0
        envFrom:
          - configMapRef:
              name: spout-env
          - secretRef:
              name: spout-secret
        volumeMounts:
          - mountPath: /app
            name: code-volume
      initContainers:
      - name: wait-kafka
        image: kafka-client:1.0.0
        command: ["sh", "-c", "kafka-console-producer.sh --broker-list $(KAFKA_ADDRESS) --topic $(KAFKA_MAIN_TOPIC)"]
        envFrom:
        - configMapRef:
            name: spout-env
      volumes:
      - name: code-volume
        hostPath:
          path: /spout
          type: Directory
