version: '3'
services:
  api_gateway:
    build: api_gateway/
    ports:
      - "8080:80"
    volumes:
      - ./api_gateway/src:/webapp
      - storage:/var/videofiles
    links:
      - video_management_service
  video_management_service:
    build: video_management_service/
    volumes:
      - storage:/var/video
    links:
      - video_processing_service
      - app_db
      - log_db
    environment:
      HOST_NAME: video_management_service
      DB_APP_NAME: videoserver
      DB_APP_USER: videoserver_user
      DB_APP_PASSWORD: videoserverPR20!
      DB_LOG_NAME: log
      DB_LOG_USER: log_user
      DB_LOG_PASSWORD: logPR20!
  app_db:
    image: mysql
    restart: on-failure:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: videoserver
      MYSQL_USER: videoserver_user
      MYSQL_PASSWORD: videoserverPR20!
    volumes:
      - db-app-data:/var/lib/mysql:rw
  video_processing_service:
    build: video_processing_service/
    volumes:
      - ./video_processing_service:/app
      - storage:/var/video
      - storage:/var/videofiles
    links:
      - log_db
    environment:
      HOST_NAME: video_processing_service
      DB_NAME: log
      DB_USER: log_user
      DB_PASSWORD: logPR20!
  log_db:
    image: mysql
    restart: on-failure:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: log
      MYSQL_USER: log_user
      MYSQL_PASSWORD: logPR20!
    volumes:
      - db-log-data:/var/lib/mysql:rw
volumes:
  storage:
  db-app-data:
  db-log-data:
