apiVersion: v1
data:
  MYSQL_DATABASE: log
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"log-db-env","creationTimestamp":null},"data":{"MYSQL_DATABASE":"log"}}
  creationTimestamp: "2020-01-17T20:34:38Z"
  name: log-db-env
  namespace: default
  resourceVersion: "196024"
  selfLink: /api/v1/namespaces/default/configmaps/log-db-env
  uid: 4802dbf6-7696-4b25-9811-db81f96633e8
