apiVersion: v1
data:
  DB_PASSWORD: bG9nUFIyMCE=
  DB_USER: bG9nX3VzZXI=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"video-processing-secret","creationTimestamp":null},"data":{"DB_PASSWORD":"bG9nUFIyMCE=","DB_USER":"bG9nX3VzZXI="}}
  creationTimestamp: "2020-01-13T19:56:37Z"
  name: video-processing-secret
  namespace: default
  resourceVersion: "61743"
  selfLink: /api/v1/namespaces/default/secrets/video-processing-secret
  uid: 12aa5417-8d94-40d7-b8d8-0f8afd194d4e
type: Opaque
