apiVersion: v1
kind: Service
metadata:
  name: video-management
  namespace: video-server
spec:
  ports:
    - port: 8080
  selector:
    app: video-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-management
  namespace: video-server
spec:
  selector:
    matchLabels:
      app: video-management
  template:
    metadata:
      labels:
        app: video-management
    spec:
      containers:
      - name: video-management
        image: docker-registry.default.svc:5000/video-server/video-management-service:1.0.1
        env:
          - name: HOST_NAME
            valueFrom:
              configMapKeyRef:
                name: video-management
                key: host-name
          - name: APP_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: video-management
                key: app-db-host
          - name: APP_DB_USER
            valueFrom:
              secretKeyRef:
                name: app-db
                key: database-user
          - name: APP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-db
                key: database-password
          - name: APP_DB_NAME
            valueFrom:
              secretKeyRef:
                name: app-db
                key: database-name
          - name: LOG_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: video-management
                key: log-db-host
          - name: LOG_DB_USER
            valueFrom:
              secretKeyRef:
                name: log-db
                key: database-user
          - name: LOG_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: log-db
                key: database-password
          - name: LOG_DB_NAME
            valueFrom:
              secretKeyRef:
                name: log-db
                key: database-name
          - name: KAFKA_ADDRESS
            valueFrom:
              secretKeyRef:
                name: apache-kafka
                key: kafka-address
          - name: KAFKA_GROUP_ID
            valueFrom:
              configMapKeyRef:
                name: video-management
                key: kafka-group-id
          - name: KAFKA_MAIN_TOPIC
            valueFrom:
              configMapKeyRef:
                name: video-management
                key: kafka-main-topic
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: /var/video
            name: storage-data
      volumes:
        - name: storage-data
          persistentVolumeClaim:
            claimName: storage
