apiVersion: v1
kind: Service
metadata:
  name: video-management
spec:
  ports:
    - port: 8080
  selector:
    app: video-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-management
spec:
  selector:
    matchLabels:
      app: video-management
  template:
    metadata:
      labels:
        app: video-management
    spec:
      containers:
      - name: video-management
        image: gdev96/video-management-service:2.0.0
        envFrom:
          - configMapRef:
              name: video-management-env
          - secretRef:
              name: video-management-secret
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: /var/video
            name: storage
      volumes:
      - name: storage
        hostPath:
          path: /storage-volume
          type: DirectoryOrCreate
