apiVersion: v1
kind: Service
metadata:
  name: apache-kafka
spec:
  ports:
    - port: 9092
  selector:
    app: apache-kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apache-kafka
spec:
  selector:
    matchLabels:
      app: apache-kafka
  serviceName: "apache-kafka"
  template:
    metadata:
      labels:
        app: apache-kafka
    spec:
      containers:
      - name: apache-kafka
        image: wurstmeister/kafka:2.12-2.4.0
        ports:
          - containerPort: 9092
        env:
          - name: BROKER_ID_COMMAND
            value: "hostname | awk -F '-' '{print $NF}'"
          - name: KAFKA_LISTENERS
            value: "PLAINTEXT://:9092"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper:2181"
