apiVersion: v1
kind: Service
metadata:
  name: storage-manager
spec:
  ports:
    - port: 80
  selector:
    app: storage-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-manager
spec:
  selector:
    matchLabels:
      app: storage-manager
  template:
    metadata:
      labels:
        app: storage-manager
    spec:
      containers:
      - name: storage-manager
        image: storage-manager:1.0.0
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /webapp
            name: code-volume
          - mountPath: /var/videofiles
            name: storage
      volumes:
      - name: code-volume
        hostPath:
          path: /storage-manager
          type: Directory
      - name: storage
        hostPath:
          path: /storage-volume
          type: DirectoryOrCreate
